import os
import glob
from pypdf import PdfReader, PdfWriter


def compress_all_local_pdfs(output_directory="compressed_output"):
    """
    Automatically detects and safely compresses EVERY PDF file in the current folder.
    """
    # Scan the current folder for any file ending with .pdf
    pdf_files = glob.glob("*.pdf")

    if not pdf_files:
        print("ℹ️ No PDF files found in the current folder.")
        print(f"👉 Please drag and drop your PDF files into your PyCharm project folder.")
        return

    # Create the output folder if it doesn't exist yet
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
        print(f"📁 Created folder: {output_directory}")

    print(f"\n🚀 Found {len(pdf_files)} PDF file(s). Starting compression...")

    for file_path in pdf_files:
        base_name = os.path.basename(file_path)

        # Skip files that have already been generated by this tool
        if base_name.startswith("compressed_"):
            continue

        output_path = os.path.join(output_directory, f"compressed_{base_name}")
        print(f"\n⚡ Optimizing: {base_name}...")

        try:
            reader = PdfReader(file_path)
            writer = PdfWriter()

            # Safe execution order: Add pages to writer first
            for page in reader.pages:
                writer.add_page(page)

            # Compress content streams within the writer scope safely
            for page in writer.pages:
                page.compress_content_streams()

            # Save the newly optimized PDF
            with open(output_path, "wb") as f:
                writer.write(f)

            # Calculate and display execution metrics
            initial_size = os.path.getsize(file_path)
            final_size = os.path.getsize(output_path)
            saved_bytes = initial_size - final_size
            savings_percentage = (saved_bytes / initial_size) * 100 if initial_size > 0 else 0

            print(f"✅ Success! Saved to: {output_path}")
            print(f"   Original Size:   {initial_size / 1024:.2f} KB")
            print(f"   Compressed Size: {final_size / 1024:.2f} KB")
            print(f"   Space Saved:     {saved_bytes / 1024:.2f} KB ({savings_percentage:.1f}%)")

        except Exception as e:
            print(f"❌ Could not compress '{base_name}'. Reason: {str(e)}")

    print("\n🏁 All operations completed!")


if __name__ == "__main__":
    compress_all_local_pdfs()